name: Slack Notify on PR Open
on:
  pull_request:
    types: [opened]
    branches:
      - main
      - develop
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Message (PR Opened)
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{
              "text": "새로운 PR이 `${{ github.event.pull_request.base.ref }}` 브랜치에 올라왔습니다!\n\n**제목**: ${{ github.event.pull_request.title }}\n**작성자**: ${{ github.event.pull_request.user.login }}\n**타겟**: `${{ github.event.pull_request.head.ref }}` → `${{ github.event.pull_request.base.ref }}`\n\n<${{ github.event.pull_request.html_url }}|PR 확인하러 가기>"
            }' \
            ${{ secrets.SLACK_WEBHOOK_URL }}